name: Trufflehog Secrets Scanning

on: [pull_request]

jobs:
  trufflehog-secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Trufflehog Actions Scan
        uses: edplato/trufflehog-actions-scan@v0.9k-beta
