---

# This runs Yelp's 'detect-secrets': https://github.com/Yelp/detect-secrets/blob/master/README.md

name: Scan Code for Secrets

on:
  pull_request:
  push:
    branches:
      - 'main'
    tags:
      - '!**'

jobs:
  check-for-secrets:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install and run blocking check
        run: |
          pip install detect-secrets
          detect-secrets-hook --baseline .secrets.baseline ./src/*

