name: Apply

on:
  push:
    branches:
      - main

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    name: Apply terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::391294193874:role/GithubActionsRole
          aws-region: us-east-2
      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: src
          auto_approve: true
          backend_config_file: src/tf.backend