name: Terraform PR Plan

on: [pull_request]

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    name: Create terraform plan          
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@b8c74de753fbcb4868bf2011fb2e15826ce973af
        with:
          role-to-assume: arn:aws:iam::391294193874:role/GithubActionsRole
          aws-region: us-east-2
      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: src
          backend_config_file: src/tf.backend
